"""Generate the work-list of Origin strings that need placing on the map.

Every table carries a free-text `Origin`. Before the database can be sliced by
region, each distinct string has to be resolved to a place and a region. This
script enumerates the strings and writes them out unmapped; filling in `place`
and `region` is a human judgement and is deliberately not attempted here.

Existing entries in schema/origins_inventory.yml are preserved, so the file can
be refreshed after new values arrive without losing work already done.

    make origins
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from suewsdb import DB_DIR, SCHEMA_DIR, dump_yaml, load_registry, load_yaml  # noqa: E402

OUT = SCHEMA_DIR / "origins_inventory.yml"

HEADER = """\
# Work-list for the geographical axis: every distinct `Origin` string in the
# database, with the tables it appears in.
#
# Generated by scripts/build_origins_inventory.py. Re-running preserves any
# `place`, `region` and `representativeness` already filled in.
#
# `region` should be one of the 22 names in db/region.yml, which is the
# vocabulary the database already uses; `null` means not yet assigned.
# `representativeness` says how far the value travels beyond its own site:
#
#   site        measured at one site, not transferable without an argument
#   city        characteristic of that city
#   regional    offered as typical of the region
#   generic     not tied to a place (defaults, dummies, sample data)
#   null        not yet assessed
"""


def main() -> int:
    registry = load_registry()
    existing = {}
    if OUT.exists():
        existing = (load_yaml(OUT) or {}).get("origins", {})

    usage = defaultdict(lambda: defaultdict(int))
    for entry in registry["tables"]:
        table = load_yaml(DB_DIR / entry["file"])
        if "Origin" not in table["columns"]:
            continue
        for record in table["entries"].values():
            value = record.get("Origin")
            if value is not None:
                usage[str(value)][entry["sheet"]] += 1

    origins = {}
    for value in sorted(usage, key=lambda v: (-sum(usage[v].values()), v)):
        prior = existing.get(value, {})
        origins[value] = {
            "count": sum(usage[value].values()),
            "tables": dict(sorted(usage[value].items())),
            "place": prior.get("place"),
            "region": prior.get("region"),
            "representativeness": prior.get("representativeness"),
        }

    mapped = sum(1 for o in origins.values() if o["region"])
    dump_yaml(
        {
            "n_distinct": len(origins),
            "n_mapped": mapped,
            "origins": origins,
        },
        OUT,
        header=HEADER,
    )
    print(f"{len(origins)} distinct Origin values, {mapped} mapped -> {OUT.relative_to(OUT.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
