"""Convert database.xlsx into the canonical per-table YAML files.

This is a format-only migration: cell values are carried across verbatim,
including -999 sentinels, trailing spaces in names and the JSON strings
embedded in Region/Country. Nothing is corrected here -- corrections belong in
their own commits so that they are reviewable against a stable base.

    make yaml
"""

from __future__ import annotations

import sys

import openpyxl

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))
from suewsdb import DB_DIR, SCHEMA_DIR, TABLES_YML, XLSX, dump_yaml, slug  # noqa: E402

TABLE_HEADER = """\
# Generated by scripts/xlsx_to_yaml.py -- edit this file, not database.xlsx.
# One entry per row, keyed by the integer ID. Columns that hold another
# table's IDs are listed under `references` in schema/tables.yml.
"""

REGISTRY_HEADER = """\
# Table registry for the SUEWS parameter database.
#
# Generated by scripts/xlsx_to_yaml.py. `id_prefixes` are the leading digits of
# the IDs a table owns, which is how an ID in a reference column is resolved
# back to its table. `columns` fixes the column order used when the workbook is
# regenerated. `references` lists the foreign keys, detected by resolving every
# 8-digit value in a column back to the table that owns that prefix.
"""

# Every primary key in the workbook is an 8-digit integer, so a value in this
# range is a candidate foreign key and a plain numeric parameter is not.
ID_MIN, ID_MAX = 10_000_000, 99_999_999


def detect_references(columns, entries, prefix_owner):
    """Map each column that holds another table's IDs to that table."""
    refs = {}
    for column in columns[1:]:
        owners = set()
        seen = 0
        for record in entries.values():
            value = record.get(column)
            if value is None:
                continue
            seen += 1
            if not isinstance(value, int) or not ID_MIN <= value <= ID_MAX:
                owners.add(None)
                break
            owners.add(prefix_owner.get(str(value)[:2]))
        if seen and None not in owners and len(owners) == 1:
            refs[column] = owners.pop()
    return refs


def main() -> int:
    wb = openpyxl.load_workbook(XLSX, data_only=True)
    DB_DIR.mkdir(exist_ok=True)
    SCHEMA_DIR.mkdir(exist_ok=True)

    # First pass: read every sheet, so that the prefix -> table map needed for
    # foreign-key detection is complete before any file is written.
    sheets = []
    prefix_owner = {}
    total_cells = 0

    for ws in wb.worksheets:
        columns = [c.value for c in ws[1]]
        if columns[0] != "ID":
            raise SystemExit(f"sheet {ws.title!r} does not start with an ID column")

        entries = {}
        for row in ws.iter_rows(min_row=2, values_only=True):
            if all(cell is None for cell in row):
                continue  # trailing blank rows carry no data
            record = dict(zip(columns, row))
            key = record.pop("ID")
            if key is None:
                raise SystemExit(f"sheet {ws.title!r} has a data row with no ID")
            if key in entries:
                raise SystemExit(f"sheet {ws.title!r} has duplicate ID {key}")
            entries[key] = record
            total_cells += sum(1 for v in row if v is not None)

        prefixes = sorted({str(k)[:2] for k in entries})
        for prefix in prefixes:
            if prefix in prefix_owner:
                raise SystemExit(
                    f"ID prefix {prefix!r} is claimed by both "
                    f"{prefix_owner[prefix]!r} and {ws.title!r}"
                )
            prefix_owner[prefix] = ws.title
        sheets.append((ws.title, columns, entries, prefixes))

    # Second pass: write the table files and the registry.
    registry = {"source": XLSX.name, "tables": []}
    total_rows = 0

    for title, columns, entries, prefixes in sheets:
        stem = slug(title)
        dump_yaml(
            {
                "table": title,
                "id_prefixes": prefixes,
                "columns": columns,
                "entries": entries,
            },
            DB_DIR / f"{stem}.yml",
            header=TABLE_HEADER,
        )

        registry["tables"].append(
            {
                "sheet": title,
                "file": f"{stem}.yml",
                "id_prefixes": prefixes,
                "n_entries": len(entries),
                "columns": columns,
                "references": detect_references(columns, entries, prefix_owner),
            }
        )
        total_rows += len(entries)
        print(f"  {title:<28} {len(entries):>4} entries -> db/{stem}.yml")

    dump_yaml(registry, TABLES_YML, header=REGISTRY_HEADER)
    print(
        f"\n{len(registry['tables'])} tables, {total_rows} entries, "
        f"{total_cells} non-empty cells -> db/ + schema/tables.yml"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
